### ISSUE TITLE
Not sure what steps to do next

### ISSUE THREAD

**Issue by dtjensen** [OpenMobileAlliance/OMA-LWM2M-DevKit#2]
I am just starting to play around with the dev kit, so this is a basic question.  When I follow the help tips, I get to the point where it tells me "The client is registered. Check the LWM2M Server then click Device Management and Service Enablement."  I click on the Device Management option, and another help tip pops up, that says that "requests from the LWM2M server are logged here..."  But I can go no further. When I click on anything in the Device Management dialog, nothing happens. 

What am I missing?  What is the next step from that point?

**Comment by mkovatsc** [comment]
You need to issue requests from your LWM2M Server :)
So, read an Instance, write a Resource, something like that. Leshan, for instance, provides the buttons for that next to the registered resources in its Web frontend.

**Comment by dtjensen** [comment]
Ahhh.... I was confused because I thought the left side window represented the client and the main window was the server... I did not know I needed to open a separate instance to interact with the server.  Thanks for the help!  That was what I needed.
