### ISSUE TITLE
Problem with update operation

### ISSUE THREAD

**Issue by dmoranj** [OpenMobileAlliance/OMA-LWM2M-DevKit#3]
I am developing a [Lightweight M2M library](https://github.com/telefonicaid/lwm2m-node-lib) for Node.js, and starting to test it against the tools provided by the OMA-LWM2M-DevKit, and I'm facing some problems. The first problem is the return path of the updates from the client: when I register with the Mozilla Plugin against my local server, my server return a Location Path with value "/rd/1" (being 1 the id of the device in the server), and expects the updates and delete operations be sent to that same path, but they are sent to "/1" instead (section 8.2.3 of the specification). Is that the expected behavior? 

The second problem concerns the state of the plugin once the error has happened: from this moment on, each time it is opened the error "ERROR: Error: Host/network unreachable" is printed, and controls doesn't seem to work anymore. The error lasts for some time and then disappears (cleaning cache and cookies and restarting the browser doesn't seem to work). It would be nice feature to have a "Reset client" button to restore the client to an out-of-the-box state.

**Comment by mkovatsc** [comment]
I am not able to reproduce the problem. What do the CoAP logs and the field "Handle for Updates" in the Registration popup say? Is the Location-Path you are sending correct?

I moved the second problem into its own issue.

**Comment by dmoranj** [comment]
This is the content of the COAP Log (that, BTW, it's not easy to cut and paste, maybe a raw version should be included):

```
CON-POST                         11949 (0) empty  Uri-path: rd, [...]
ACK-2.01 Created               11949      empty  Location-path: /rd/2
CON-PUT                            11950 (0) empty  Uri-path: 2
ACK-4.04 Not Found           11949      empty
```

The problem here is the option `Uri-path: 2`.  The URL I'm receiving in the Server end is `/2?lt=30&b=U` and, maybe I'm wrong with this but, if a location path of `/rd/2` is returned I would expect a `/rd/2` path to be used in future interactions. Am I misunderstanding any part of the specification?

**Comment by mkovatsc** [comment]
I still cannot reproduce the issue.
1. The response (ACK 11949) has the correct Location-Path.
2. The handler does a `Lwm2mDevKit.registrationHandle = message.getLocation();`.
3. Please check the "Handle for Updates" field in the Registration popup, which should be equal to the Location-Path in the response (modulo the initial slash).
4. When I configure my Server to use single-digit integers for the handle and test the DevKit Registration Update, everything works fine.

**Comment by dmoranj** [comment]
Now that the network problems were solved, I've tried agin and I consistently obtain the same results: the Location-path received by the Dev Kit is '/rd/1' (read from the console), the value of the "Handle for Updates" field is "//rd/1", but the url sent by the update command is "/1?lt=30&b=U" when I expected to receive "/rd/1?lt=30&b=U". 

Am I missing something on the specification? Is the LWM2M client supposed to remove the '/rd' prefix from the Location-path before using it in subsequent requests? Is it possible that I have something in my local installation of the Firefox plugin causing this problem?

**Comment by dmoranj** [comment]
I've also noticed that the previous "Network Error" behavior does not reproduce if the Server uses IPv6 (I was using IPv4 in the first tests). Does the DevKit expect the clients to use exclusively IPv6?

**Comment by dmoranj** [comment]
Playing with server on http://leshan.eclipse.org/ I've realized that the Location Path returned by the server is 'rd/O0MuFl1wgi' without an initial slash character. This behavior may explain why the "Handle for updates" field has a double slash in my case and why it's sending a single number (via a parsing error). But I wonder whether this behavior is the one specified by the spec or not. Doesn't seem to be the case, looking at page 54 of the specification (where the example registration returns '/rd/5a3f'). Is the spec wrong at this point? Or is there any other part of the spec where the registration is better described? Is the format of the content of the Location-path option left to the developer to choose?

**Comment by mkovatsc** [comment]
You should start with good understanding and clean implementation of CoAP before implementing the LWM2M TS. Please have a close look at the RFC (https://tools.ietf.org/html/rfc7252). You can have a close look at working CoAP implementations using Wireshark and then compare with yours.
