### ISSUE TITLE
Error: Host/network unreachable (originally by dmoranj)

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA-LWM2M-DevKit#4]
@dmoranj: The second problem concerns the state of the plugin once the error has happened: from this moment on, each time it is opened the error "ERROR: Error: Host/network unreachable" is printed, and controls doesn't seem to work anymore. The error lasts for some time and then disappears (cleaning cache and cookies and restarting the browser doesn't seem to work). It would be nice feature to have a "Reset client" button to restore the client to an out-of-the-box state.

**Comment by mkovatsc** [comment]
Currently there is now hard state. Pressing F5 completely resets the DevKit.

The "Host/network unreachable" is more fundamental and occurs when there is no network connectivity, missing routes, the hostname unresolveable, or the interface gone. When using virtual interfaces (e.g., tun0 for a border router) you need to reload after tearing down and restarting the virtual interface.

What and where is your LWM2M Server?

**Comment by dmoranj** [comment]
My LWM2M Server is on the localhost, and uses my own implementation of the LWM2M protocol. I'm not using any virtual interface, also, and I've checked I'm able to connect to my server with my own clients. I will try to investigate it further to see where the network connectivity issues might come from.

**Comment by mkovatsc** [comment]
Besides the online sandbox I am testing with a local Leshan server (also coap+lwm2m://localhost/). Maybe check to which addresses your server binds and what the Ping/Ready popup in the DevKit says under "Device Address."

**Comment by dmoranj** [comment]
I'm having trouble with PING, as well... I suspect there is some trouble with the COAP library I'm using, but at first everything seems to be following the specification, I'm struggling to find what's wrong with the interaction. Sending PINGs with the LWM2M-DevKit I'm replying with a `RST-2.05 Content` (read from the DevKit console), but the ping popup keeps saying: `The remote address does not respond to COAP Ping: CON-EMPTY timed out`. But the message response arrives almost immediately, so I don't understand what the problem may be. Can you provide me with an example of the message the COAP Ping is expected (the specification is somewhat ambiguous about it: "Provoking a Reset message (e.g., by sending an Empty Confirmable message) is also useful as an inexpensive check of the liveness of an endpoint  ("CoAP ping")")

**Comment by mkovatsc** [comment]
RSTs are always empty (code = 0).
Use the DevKit together with leshan.eclipse.org to see a workingexample.

**Comment by dmoranj** [comment]
Ok. Now, the Ping works, that was the problem. I'll modify that on the server and retry everything else. Thanks.

**Comment by dmoranj** [comment]
Updating the server to provide a correct response to Ping, seem to solve this issue completely.

Thanks for your assistance

**Comment by Megan-OMA** [comment]
Closing 25-May-16
